### ISSUE TITLE
Landsat8Query may produce invalid query strings

### ISSUE THREAD

**Issue by schBen** [azavea/scala-landsat-util#7]
In non-English environments, the methods contains, intersects, and searchTerms can produce invalid query strings. That is because the local decimal mark is used when formatting doubles to strings, so that there may be a comma "," instead of a dot ".".
Also, searchTerms can insert "+AND+" when a neighboring string is empty.

**Comment by schBen** [comment]
I made pull request #8 to fix this issue.

**Comment by pomadchin** [comment]
Resolved in #8, thx @schBen !
